### ISSUE TITLE
执行安装命令时，无法安装

### ISSUE THREAD

**Issue by adays906** [quarkcms/quark-cms#9]
安装 quark-cms 时，已经正常安装了 Laravel 6.0 ，也已经正常安装了 composer 的依赖后：  

`# 第二步，然后运行下面的命令完成安装
php artisan quark:install`

按说明要求，执行这步操作时报下面错误：

`  There are no commands defined in the "quark" namespace.`

（ 题外话： 安装 QuarkAdmin 时，发现在 Laravel 6.0 基础环境上就能正常安装； 6.* 不能正常安装，）

**Comment by tangtanglove** [comment]
好的，我测试一下

**Comment by tangtanglove** [comment]
刚才测试了，我这儿没问题，你的环境是什么，麻烦发一下

**Comment by adays906** [comment]
我是 win 10 64位系统,
安装的 phpstudy 配置服务器环境，
php7.3.4 + Apache2.4.39 + Mysql5.7.26
npm 6.14.8
yarn 1.22.5
composer 2.0.7

**Comment by tangtanglove** [comment]
不需要安装laravel，这是一个系统，不是composer包

**Comment by adays906** [comment]
直接下载代码后，按步骤安装，成功。能打开前端和后端。完美。

**Comment by tangtanglove** [comment]
好的
